// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type PostApiEventsSourceEventsData = {
  body?: {
    type: string;
    uuid: string;
    payload?: {
      [key: string]: unknown;
    };
    attributions?: Array<{
      type: string;
      value: string;
    }>;
  };
  path: {
    source: string;
  };
  query?: never;
  url: "/api/events/{source}/events";
};

export type PostApiEventsSourceEventsErrors = {
  /**
   * Invalid request body or parameters
   */
  400: unknown;
  /**
   * Source not found
   */
  404: unknown;
};

export type PostApiEventsSourceEventsResponses = {
  /**
   * Event recorded successfully
   */
  200: unknown;
};

export type PostApiAuthKeysData = {
  body?: {
    owner: string;
    quotas: {
      requestsPerSecond: number;
      requestsPerDay: number;
      totalRequests: number;
    };
  };
  path?: never;
  query?: never;
  url: "/api/auth/keys";
};

export type PostApiAuthKeysErrors = {
  /**
   * Invalid request body
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
};

export type PostApiAuthKeysResponses = {
  /**
   * API key created successfully
   */
  201: unknown;
};

export type DeleteApiAuthKeysKeyData = {
  body?: never;
  path: {
    key: string;
  };
  query?: never;
  url: "/api/auth/keys/{key}";
};

export type DeleteApiAuthKeysKeyErrors = {
  /**
   * Unauthorized (requires master api key)
   */
  401: unknown;
};

export type DeleteApiAuthKeysKeyResponses = {
  /**
   * API key deleted successfully
   */
  200: unknown;
};

export type GetApiAuthKeysKeyData = {
  body?: never;
  path: {
    key: string;
  };
  query?: never;
  url: "/api/auth/keys/{key}";
};

export type GetApiAuthKeysKeyErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type GetApiAuthKeysKeyResponses = {
  /**
   * API key details
   */
  200: unknown;
};

export type PatchApiAuthKeysKeyData = {
  body?: {
    owner?: string;
    quotas?: {
      requestsPerSecond?: number;
      requestsPerDay?: number;
      totalRequests?: number;
    };
    enabled?: boolean;
  };
  path: {
    key: string;
  };
  query?: never;
  url: "/api/auth/keys/{key}";
};

export type PatchApiAuthKeysKeyErrors = {
  /**
   * Invalid request body
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type PatchApiAuthKeysKeyResponses = {
  /**
   * API key updated successfully
   */
  200: unknown;
};

export type GetApiAuthUsageData = {
  body?: never;
  path?: never;
  query?: {
    apiKey?: string;
  };
  url: "/api/auth/usage";
};

export type GetApiAuthUsageErrors = {
  /**
   * Bad Request: apiKey query param is required for master key users
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * API key not found
   */
  404: unknown;
};

export type GetApiAuthUsageResponses = {
  /**
   * Usage statistics
   */
  200: unknown;
};
